feat(PTP-549): split tests
ConsenSys/infura-sdk pull request #73
Opened 2022-07-12 14:11 UTC by salimtb

2022-07-12 14:49 UTC, efecarranza approved these changes
LGTM but I'd prefix the files with "erc721mintable.royalty..." because we have more contracts coming up, so we'll need to differentiate.

2022-07-13 08:37 UTC, kalote requested changes

2022-07-13 08:37 UTC, kalote commented on integration-test/royalty.test.js
> +    await server.listen(8545);
All the ganache setup can be extracted into a separate file for easy re-use in all tests (DRY)
- options / server
- parsing keys.json & extracting addr & private keys
- server closing

2022-07-13 11:57 UTC, kalote approved these changes

2022-07-13 12:15 UTC, merged