ErrorLogger updated on ContractFactory, Provider and Signer.
ConsenSys/infura-sdk pull request #79
Opened 2022-08-02 17:15 UTC by danielpavelicconsensys

Final PR for ErrorLogger updates.

2022-08-09 14:51 UTC, kalote requested changes
one small modification

2022-08-09 15:06 UTC, salimtb commented
i think we can make it better when we will move to Typescript by using generic types, here is a proposition but as the PR is in JS i'm wondering if we can create a ticket for that and implement it in the TS version: 
`function throwIfFalsy<T>(x: T | null | undefined, message: string, location: string): asserts x is T {
    if (!x) {
        throw new Error(message);
        throw new Error(
              errorLogger({
                location,
                message
              }),
            );
    }
}`

example of use here:

`throwIfFalsy(rpcUrl, ERROR_LOG.location.Provider_getProvider, ERROR_LOG.message.no_rpcURL)`

2022-08-10 15:15 UTC, danielpavelicconsensys commented on src/lib/Provider/Provider.js
> +          message: ERROR_LOG.message.no_privateKey,
changed, tx

2022-08-11 12:26 UTC, salimtb approved these changes

2022-08-16 12:45 UTC, kalote commented on integration-test/erc721mintable.readContract.test-integration.js
> +        attributes: [],
FYI, this is linked to this => https://github.com/ConsenSys/nft-api-apps/issues/113

2022-08-16 12:45 UTC, kalote approved these changes

2022-08-16 13:45 UTC, merged