ERC721UserMintable -> Template 2
ConsenSys/infura-sdk pull request #81
Opened 2022-08-12 13:36 UTC by efecarranza

# Changelog

ERC721UserMintable (Template 2):

Add new contract file.
Add new error messages.
Add new ABI.
Add new unit tests.
Add new integration tests.

2022-08-18 13:28 UTC, salimtb commented on integration-test/erc721usermintable.contract.test-integration.js
> +      IPFS,
IPFS will be a separated module , with another auth, you can delete this line .
example: 
`const ipfs = new IPFS( ...... ) , ipfs,uploadFIle(...)`

2022-08-18 13:28 UTC, salimtb commented on integration-test/erc721usermintable.contract.test-integration.js
> +    await server.close();
you don't need to open and close the connection to ganach, we do it in a global scope in the file `setupTests.js`

2022-08-18 13:28 UTC, salimtb commented on src/lib/ContractTemplates/ERC721UserMintable.js
> +    if (symbol === undefined) {
what if `symbol === null ` ??? i think it's better if you use `!symbol`, i know it's a copy past but are we allowed `null` as value for symbol ?

2022-08-19 09:46 UTC, kalote requested changes
- Check the JSDoc of the ERC721UserMintable class
- there is some change to do on the SDK load & deploy method, no?
- Missing usage.js demonstration

2022-08-19 09:46 UTC, kalote commented on src/lib/ContractTemplates/ERC721UserMintable.js
> +   * @param {string} maxSupply Price to mint one token
typo => remove "maxSupply" (it should be price)

2022-08-19 09:46 UTC, kalote commented on src/lib/ContractTemplates/ERC721UserMintable.js
> +   * (link to a JSON file describing the contract's metadata)
missing "maxTokenRequest" JSDoc info

2022-08-19 09:46 UTC, kalote commented on src/lib/ContractTemplates/ERC721UserMintable.js
> +   * @param price Price of the mint (per token) in Ether as a string
missing type for param

2022-08-23 18:04 UTC, efecarranza commented
@kalote updated. i didn't add an example in `usage.js` however. 
i don't think we need to do an example of each in that file, rather, it's a guide on how to set things up and how the SDK works.
we have the docs to add all the available templates.

2022-08-25 13:58 UTC, salimtb approved these changes

2022-09-06 14:28 UTC, kalote approved these changes

2022-09-06 14:50 UTC, merged